services:
  makerepo-rclone:
    container_name: makerepo-rclone
    build:
      context: .
    environment:
      - MWT_GITHUB_URL=https://api.github.com/repos/rclone/rclone/releases
      - REPREPRO_ORIGIN=mirror.mwt.me
      - REPREPRO_LABEL=Rclone
      - REPREPRO_ARCHITECTURES=amd64 i386 arm64 armhf armel mips mipsel
    env_file:
      - secret.env
    volumes:
      - /mnt/storage/mirror/rclone:/dist
      - reprepro-db-rclone:/root/reprepro/db
    restart: "unless-stopped"
  makerepo-zoom:
    container_name: makerepo-zoom
    build:
      context: .
    environment:
      - MWT_DIRECT_DOWNLOADS=https://zoom.us/client/latest/zoom_amd64.deb https://zoom.us/client/latest/zoom_x86_64.rpm
      - REPREPRO_ORIGIN=mirror.mwt.me
      - REPREPRO_LABEL=Zoom
      - REPREPRO_ARCHITECTURES=amd64
    env_file:
      - secret.env
    volumes:
      - /mnt/storage/mirror/zoom:/dist
      - reprepro-db-zoom:/root/reprepro/db
    restart: "unless-stopped"
  makerepo-rstudio:
    container_name: makerepo-rstudio
    build:
      context: .
    environment:
      - MWT_DIRECT_DOWNLOADS=https://rstudio.org/download/latest/stable/desktop/focal/rstudio-latest-amd64.deb#focal https://rstudio.org/download/latest/stable/desktop/jammy/rstudio-latest-amd64.deb#jammy https://rstudio.org/download/latest/stable/desktop/rhel9/rstudio-latest-x86_64.rpm#el9
      - REPREPRO_ORIGIN=mirror.mwt.me
      - REPREPRO_LABEL=RStudio
      - REPREPRO_CODENAMES=focal jammy
      - REPREPRO_ARCHITECTURES=amd64
    env_file:
      - secret.env
    volumes:
      - /mnt/storage/mirror/rstudio:/dist
      - reprepro-db-rstudio:/root/reprepro/db
    restart: "unless-stopped"
volumes:
  reprepro-db-rclone:
  reprepro-db-zoom:
  reprepro-db-rstudio:
